# Generated by Django 6.1 on 2026-08-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_hours', models.FloatField()),
                ('attendance', models.FloatField()),
                ('previous_marks', models.FloatField()),
                ('assignments', models.IntegerField()),
                ('predicted_marks', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
